# Pandas：从脏数据到可靠分析

**学习主线**

`读取 → 检查 → 清洗 → 变换 → 汇总 → 合并 → 可视化`

Pandas 的核心是带标签的一维 `Series` 和二维 `DataFrame`。  
本笔记使用一份小型订单表贯穿示例，避免每节换数据导致理解断裂。

## 初学者使用 Pandas 的心智模型

`DataFrame` 可以看成一张带行标签和列标签的表，也可以类比为一组长度相同、类型可能不同的列：

- `Series`：一列数据 + index；
- `DataFrame`：多列 Series 共享一套行 index；
- 一行通常代表一个样本或事件；
- 一列通常代表一个变量。

与 NumPy 最大的区别是：**Pandas 会按标签对齐数据**。两个 Series 相加时，index 相同的值才会相加，而不是只看内存位置。

阅读 Pandas 代码时先问：

1. 一行代表什么？
2. index 是否有业务含义？
3. 当前操作会筛掉行、增加列，还是改变粒度？
4. `groupby` 后一行代表什么？
5. `merge` 的键是否唯一，连接后行数为什么变化？

选择数据时：

- `.loc`：按标签；
- `.iloc`：按整数位置；
- 布尔条件：按业务规则筛选。

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# set_option 只影响显示方式，不改变 DataFrame 中的数据。
pd.set_option("display.max_columns", 20)
print("Pandas version:", pd.__version__)

/opt/anaconda3/lib/python3.13/site-packages/pandas/core/computation/expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

Pandas version: 3.0.1

## 1. 创建统一示例数据

每一行是一笔订单，每一列是一个变量。真实项目通常通过 `pd.read_csv()` 或 `pd.read_excel()` 读取。

In [2]:
# DataFrame 接收“列名 -> 一列数据”的字典；各列长度必须一致。
orders = pd.DataFrame({
    "order_id": [1001, 1002, 1003, 1004, 1005, 1006],
    "customer": ["Alice", "Bob", "Alice", "Chen", "Bob", "Dina"],
    "city": ["Beijing", "Shanghai", "Beijing", "Shenzhen", "Shanghai", None],
    "category": ["Book", "Tech", "Book", "Food", "Tech", "Food"],
    "quantity": [2, 1, 3, 5, 2, 4],
    "unit_price": [45.0, 399.0, 42.0, 18.0, np.nan, 25.0],
    "order_date": ["2026-01-02", "2026-01-03", "2026-01-05",
                   "2026-01-06", "bad-date", "2026-01-08"],
})
orders

   order_id customer      city category  quantity  unit_price  order_date
0      1001    Alice   Beijing     Book         2        45.0  2026-01-02
1      1002      Bob  Shanghai     Tech         1       399.0  2026-01-03
2      1003    Alice   Beijing     Book         3        42.0  2026-01-05
3      1004     Chen  Shenzhen     Food         5        18.0  2026-01-06
4      1005      Bob  Shanghai     Tech         2         NaN    bad-date
5      1006     Dina       NaN     Food         4        25.0  2026-01-08

### 其他常见 DataFrame 数据类型

一个 DataFrame 的不同列可以使用不同 dtype，例如浮点数、整数、字符串、时间戳和分类类型。分类类型适合重复值较多的有限类别。

In [ ]:
mixed_types = pd.DataFrame({
    "count": pd.Series([1, 2, 3], dtype="Int64"),
    "ratio": [0.1, 0.2, 0.3],
    "created_at": [pd.Timestamp("2026-01-01")] * 3,
    "grade": pd.Categorical(["A", "B", "A"]),
})

print(mixed_types)
print(mixed_types.dtypes)

   count  ratio created_at grade
0      1    0.1 2026-01-01     A
1      2    0.2 2026-01-01     B
2      3    0.3 2026-01-01     A
count                  Int64
ratio                float64
created_at    datetime64[us]
grade               category
dtype: object

## 2. 第一轮检查：不要一上来就分析

常用检查：

- `head()` / `sample()`：观察真实值；
- `shape`：行列数；
- `info()`：类型和非空数量；
- `describe()`：数值分布；
- `isna().sum()`：每列缺失数；
- `duplicated()`：重复行。

In [4]:
print("shape:", orders.shape)
print("\n缺失数:\n", orders.isna().sum())
print("\n重复行数:", orders.duplicated().sum())
print("\n数值摘要:\n", # select_dtypes 先选数值列；describe 再统计数量、均值、分位数等。
orders.select_dtypes("number").describe())
orders.info()

shape: (6, 7)

缺失数:
 order_id      0
customer      0
city          1
category      0
quantity      0
unit_price    1
order_date    0
dtype: int64

重复行数: 0

数值摘要:
           order_id  quantity  unit_price
count     6.000000  6.000000    5.000000
mean   1003.500000  2.833333  105.800000
std       1.870829  1.471960  164.294553
min    1001.000000  1.000000   18.000000
25%    1002.250000  2.000000   25.000000
50%    1003.500000  2.500000   42.000000
75%    1004.750000  3.750000   45.000000
max    1006.000000  5.000000  399.000000
<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    6 non-null      int64
 1   customer    6 non-null      str
 2   city        5 non-null      str
 3   category    6 non-null      str
 4   quantity    6 non-null      int64
 5   unit_price  5 non-null      float64
 6   order_date  6 non-null      str
dtypes: float64(1), int64(2), str(4)
memory usage: 613.0 bytes

### 日期索引与 DataFrame 结构属性

`pd.date_range` 可以创建规则日期索引。检查 DataFrame 时要区分：

- `.index`：行标签；
- `.columns`：列标签；
- `.dtypes`：每列类型；
- `.to_numpy()`：不带标签的 NumPy 数据；
- `.T`：行列转置。

In [5]:
# date_range 生成规则日期索引：从起点开始，共 4 天，频率为每天。
dates = pd.date_range("2026-01-01", periods=4, freq="D")
dated_frame = pd.DataFrame(
    np.arange(12).reshape(4, 3),
    index=dates,
    columns=["A", "B", "C"],
)

print(dated_frame)
print("index:", dated_frame.index)
print("columns:", dated_frame.columns.tolist())
print("dtypes:\n", dated_frame.dtypes)
print("NumPy shape:", dated_frame.to_numpy().shape)
print("转置 shape:", dated_frame.T.shape)
print("是否存在任何缺失值:", np.any(dated_frame.isna().to_numpy()))

            A   B   C
2026-01-01  0   1   2
2026-01-02  3   4   5
2026-01-03  6   7   8
2026-01-04  9  10  11
index: DatetimeIndex(['2026-01-01', '2026-01-02', '2026-01-03', '2026-01-04'], dtype='datetime64[us]', freq='D')
columns: ['A', 'B', 'C']
dtypes:
 A    int64
B    int64
C    int64
dtype: object
NumPy shape: (4, 3)
转置 shape: (3, 4)
是否存在任何缺失值: False

## 3. `Series` 与标签对齐

Pandas 运算会按索引标签对齐，而不是只按位置。标签对不上时会产生缺失值。

In [6]:
# Series 同时保存值和 index；运算时会先按 index 标签对齐。
left = pd.Series([10, 20], index=["a", "b"])
right = pd.Series([1, 2], index=["b", "c"])

print(left + right)
print("\n若希望缺失标签按 0 处理:")
print(left.add(right, fill_value=0))

a     NaN
b    21.0
c     NaN
dtype: float64

若希望缺失标签按 0 处理:
a    10.0
b    21.0
c     2.0
dtype: float64

## 4. 选列、选行与筛选

- `df["col"]`：单列 `Series`；
- `df[["a", "b"]]`：多列 `DataFrame`；
- `.loc[行标签, 列标签]`：按标签；
- `.iloc[行位置, 列位置]`：按位置。

> `.ix` 已被删除，不要再使用。

In [7]:
# loc[行条件, 列标签]：这里按业务条件筛行，并只取指定列。
print(orders.loc[orders["quantity"] >= 3,
                 ["order_id", "customer", "quantity"]])

print("\n前 3 行、前 2 列:")
# iloc 按整数位置选择：前 3 行、前 2 列。
print(orders.iloc[:3, :2])

# query 用字符串表达筛选条件，列名可直接写在表达式中。
selected = orders.query("category == 'Tech' and quantity >= 1")
selected

   order_id customer  quantity
2      1003    Alice         3
3      1004     Chen         5
5      1006     Dina         4

前 3 行、前 2 列:
   order_id customer
0      1001    Alice
1      1002      Bob
2      1003    Alice

   order_id customer      city category  quantity  unit_price  order_date
1      1002      Bob  Shanghai     Tech         1       399.0  2026-01-03
4      1005      Bob  Shanghai     Tech         2         NaN    bad-date

多个布尔条件要分别加括号，并使用 `&`、`|`、`~`，不能用标量逻辑运算符 `and`、`or`。

In [8]:
mask = (
    # isin 对每个元素判断是否属于给定集合，返回布尔 Series。
orders["city"].isin(["Beijing", "Shanghai"])
    & (orders["quantity"] >= 2)
)
orders.loc[mask, ["customer", "city", "quantity"]]

  customer      city  quantity
0    Alice   Beijing         2
2    Alice   Beijing         3
4      Bob  Shanghai         2

## 5. 安全修改与新增列

链式索引可能产生 `SettingWithCopyWarning`。先明确筛选并 `.copy()`，再用 `.loc` 或 `.assign()`。

In [9]:
clean = orders.copy()

# errors='coerce'：无法解析的文本变成 NaT，便于统一发现和处理
# to_datetime 解析日期；无法解析的值在 errors="coerce" 下变成 NaT。
clean["order_date"] = pd.to_datetime(clean["order_date"], errors="coerce")
# fillna 用中位数替换缺失价格；median 会忽略 NaN。
clean["unit_price"] = clean["unit_price"].fillna(clean["unit_price"].median())
clean["city"] = clean["city"].fillna("Unknown")

# assign 返回增加新列后的 DataFrame；lambda 中的 df 是当前表。
clean = clean.assign(
    revenue=lambda df: df["quantity"] * df["unit_price"],
    is_large=lambda df: df["quantity"] >= 3,
)
clean

,order_id,customer,city,category,quantity,unit_price,order_date,revenue,is_large
0,1001,Alice,Beijing,Book,2,45.0,2026-01-02,90.0,False
1,1002,Bob,Shanghai,Tech,1,399.0,2026-01-03,399.0,False
2,1003,Alice,Beijing,Book,3,42.0,2026-01-05,126.0,True
3,1004,Chen,Shenzhen,Food,5,18.0,2026-01-06,90.0,True
4,1005,Bob,Shanghai,Tech,2,42.0,NaT,84.0,False
5,1006,Dina,Unknown,Food,4,25.0,2026-01-08,100.0,True

## 6. 缺失值与数据类型

处理缺失值前先问：为什么缺失？随机缺失、业务上“不适用”、还是采集错误？  
`dropna()` 会丢行，不应作为无条件默认操作。

In [10]:
print(clean.dtypes)
print("\n日期解析失败数:", clean["order_date"].isna().sum())

# nullable dtype 可以同时保存整数和缺失值
example = pd.Series([1, None, 3], dtype="Int64")
print(example, example.dtype)

order_id               int64
customer                 str
city                     str
category                 str
quantity               int64
unit_price           float64
order_date    datetime64[us]
revenue              float64
is_large                bool
dtype: object

日期解析失败数: 1
0       1
1    <NA>
2       3
dtype: Int64 Int64

### 检测、删除与填补缺失值

- `isna()` / `isnull()`：检测缺失；
- `notna()` / `notnull()`：检测非缺失；
- `dropna()`：删除含缺失值的行或列；
- `fillna()`：填补缺失值。

`isnull` 与 `isna` 等价。删除前要先判断缺失原因和删除后剩余样本量。

In [11]:
missing_demo = pd.DataFrame({
    "A": [1.0, np.nan, 3.0],
    "B": [10.0, 20.0, np.nan],
})

print("isnull:\n", missing_demo.isnull())
print("notnull:\n", missing_demo.notnull())
print("删除任何含缺失的行:\n", missing_demo.dropna())
print("按列均值填补:\n",
      missing_demo.fillna(missing_demo.mean()))

isnull:
        A      B
0  False  False
1   True  False
2  False   True
notnull:
        A      B
0   True   True
1  False   True
2   True  False
删除任何含缺失的行:
      A     B
0  1.0  10.0
按列均值填补:
      A     B
0  1.0  10.0
1  2.0  20.0
2  3.0  15.0

## 7. 字符串与日期

使用 `.str` 批量处理字符串，使用 `.dt` 提取日期部分；这些操作保留索引。

In [12]:
clean["customer_upper"] = clean["customer"].str.strip().str.upper()
clean["order_month"] = clean["order_date"].dt.to_period("M")
clean["weekday"] = clean["order_date"].dt.day_name()

clean[["customer_upper", "order_date", "order_month", "weekday"]]

  customer_upper order_date order_month   weekday
0          ALICE 2026-01-02     2026-01    Friday
1            BOB 2026-01-03     2026-01  Saturday
2          ALICE 2026-01-05     2026-01    Monday
3           CHEN 2026-01-06     2026-01   Tuesday
4            BOB        NaT         NaT       NaN
5           DINA 2026-01-08     2026-01  Thursday

## 8. 排序、去重与频数

In [13]:
print(clean.sort_values(["revenue", "quantity"],
                        ascending=[False, False]).head(3))
print("\n类别频数:\n", clean["category"].value_counts(dropna=False))

# subset 指定“哪些列相同才算重复”
deduplicated = clean.drop_duplicates(subset=["order_id"], keep="last")
print("去重后行数:", len(deduplicated))

   order_id customer      city category  quantity  unit_price order_date  \
1      1002      Bob  Shanghai     Tech         1       399.0 2026-01-03
2      1003    Alice   Beijing     Book         3        42.0 2026-01-05
5      1006     Dina   Unknown     Food         4        25.0 2026-01-08

   revenue  is_large customer_upper order_month   weekday
1    399.0     False            BOB     2026-01  Saturday
2    126.0      True          ALICE     2026-01    Monday
5    100.0      True           DINA     2026-01  Thursday

类别频数:
 category
Book    2
Tech    2
Food    2
Name: count, dtype: int64
去重后行数: 6

### 按索引排序与按值排序

- `sort_index()`：按行索引或列名排序；
- `sort_values()`：按一列或多列的值排序；
- 多列排序可为每列分别指定升降序。

In [14]:
unsorted = pd.DataFrame(
    {"score": [88, 95, 88], "age": [22, 20, 19]},
    index=["c", "a", "b"],
)

print("按索引:\n", unsorted.sort_index())
print("按 score 降序、age 升序:\n",
      unsorted.sort_values(
          ["score", "age"],
          ascending=[False, True],
      ))

按索引:
    score  age
a     95   20
b     88   19
c     88   22
按 score 降序、age 升序:
    score  age
a     95   20
b     88   19
c     88   22

## 9. `groupby`：拆分、计算、合并

先明确“分组键”和“指标”，再决定聚合函数。命名聚合能直接得到清楚的列名。

In [15]:
category_summary = (
    # groupby 按 category 拆分数据；as_index=False 让分组键保留为普通列。
clean.groupby("category", as_index=False)
    .agg(
        order_count=("order_id", "nunique"),
        total_quantity=("quantity", "sum"),
        total_revenue=("revenue", "sum"),
        average_price=("unit_price", "mean"),
    )
    .sort_values("total_revenue", ascending=False)
)
category_summary

  category  order_count  total_quantity  total_revenue  average_price
2     Tech            2               3          483.0          220.5
0     Book            2               5          216.0           43.5
1     Food            2               9          190.0           21.5

`agg` 缩减行数；`transform` 返回与原表等长的结果，适合计算“组内占比”“组内均值差”等特征。

In [16]:
# transform 返回与原表等长的结果，把每组总收入放回该组每一行。
clean["category_revenue"] = (
    clean.groupby("category")["revenue"].transform("sum")
)
clean["revenue_share"] = clean["revenue"] / clean["category_revenue"]

clean[["order_id", "category", "revenue", "revenue_share"]]

   order_id category  revenue  revenue_share
0      1001     Book     90.0       0.416667
1      1002     Tech    399.0       0.826087
2      1003     Book    126.0       0.583333
3      1004     Food     90.0       0.473684
4      1005     Tech     84.0       0.173913
5      1006     Food    100.0       0.526316

## 10. 合并：`concat` 与 `merge`

- `concat`：堆叠结构相同的表；
- `merge`：根据键连接不同信息；
- `validate`：声明预期关系，能及时发现重复键导致的行数膨胀。

In [17]:
customers = pd.DataFrame({
    "customer": ["Alice", "Bob", "Chen", "Dina"],
    "segment": ["VIP", "Regular", "Regular", "VIP"],
})

# merge 根据键连接两张表；结果行数取决于两边键是否唯一。
enriched = clean.merge(
    customers,
    on="customer",
    how="left",
    # validate 主动声明“多笔订单 -> 一个客户”，键关系不符会报错。
validate="many_to_one",  # 多笔订单对应一个客户属性
    indicator=True,
)
print(enriched[["order_id", "customer", "segment", "_merge"]])

   order_id customer  segment _merge
0      1001    Alice      VIP   both
1      1002      Bob  Regular   both
2      1003    Alice      VIP   both
3      1004     Chen  Regular   both
4      1005      Bob  Regular   both
5      1006     Dina      VIP   both

In [18]:
first_half = clean.iloc[:3]
second_half = clean.iloc[3:]
# concat 按行拼回两部分；ignore_index=True 重新生成 0..n-1 索引。
restored = pd.concat([first_half, second_half], ignore_index=True)

print("恢复后的 shape:", restored.shape)

恢复后的 shape: (6, 14)

### `concat`：相同列与不同列

`concat` 主要负责沿某个轴堆叠：

- `axis=0`：按行追加；
- `axis=1`：按列并排；
- `join="outer"`：保留所有标签，缺少处填 NaN；
- `join="inner"`：只保留共有标签；
- `ignore_index=True`：重新生成连续行索引。

In [19]:
part_a = pd.DataFrame({"a": [1, 2], "b": [3, 4]})
part_b = pd.DataFrame({"a": [5], "b": [6]})
different = pd.DataFrame({"b": [7], "c": [8]})

print("相同结构纵向合并:")
print(pd.concat([part_a, part_b], ignore_index=True))

print("\n不同列 outer:")
print(pd.concat([part_a, different], join="outer",
                ignore_index=True))

print("\n不同列 inner:")
print(pd.concat([part_a, different], join="inner",
                ignore_index=True))

相同结构纵向合并:
   a  b
0  1  3
1  2  4
2  5  6

不同列 outer:
     a  b    c
0  1.0  3  NaN
1  2.0  4  NaN
2  NaN  7  8.0

不同列 inner:
   b
0  3
1  4
2  7

### `merge`：数据库风格连接

`merge` 根据键匹配行。最重要的是先判断键关系：

- one-to-one：两边键都唯一；
- one-to-many：一边唯一，另一边重复；
- many-to-many：两边都重复，结果行数可能成倍增加。

建议总是使用 `validate=` 声明预期关系。

In [20]:
left = pd.DataFrame({
    "key": ["K0", "K1", "K2", "K3"],
    "value": [10, 20, 30, 40],
})
right = pd.DataFrame({
    "key": ["K0", "K1", "K2"],
    "label": ["A", "B", "C"],
})

for how in ["inner", "left", "right", "outer"]:
    merged = pd.merge(
        left,
        right,
        on="key",
        how=how,
        indicator=True,
        validate="one_to_one",
    )
    print(f"\n{how}:")
    print(merged)

inner:
  key  value label _merge
0  K0     10     A   both
1  K1     20     B   both
2  K2     30     C   both

left:
  key  value label     _merge
0  K0     10     A       both
1  K1     20     B       both
2  K2     30     C       both
3  K3     40   NaN  left_only

right:
  key  value label _merge
0  K0     10     A   both
1  K1     20     B   both
2  K2     30     C   both

outer:
  key  value label     _merge
0  K0     10     A       both
1  K1     20     B       both
2  K2     30     C       both
3  K3     40   NaN  left_only

### 多列键、索引连接与重名列

- 多列键：`on=["key1", "key2"]`；
- 索引连接：`left_index=True, right_index=True`；
- 重名非键列：用 `suffixes=("_left", "_right")` 区分。

In [21]:
left_multi = pd.DataFrame({
    "group": ["A", "A", "B"],
    "year": [2025, 2026, 2026],
    "score": [80, 90, 85],
})
right_multi = pd.DataFrame({
    "group": ["A", "A", "B"],
    "year": [2025, 2026, 2026],
    "score": [82, 93, 88],
})

multi_key = left_multi.merge(
    right_multi,
    on=["group", "year"],
    suffixes=("_exam1", "_exam2"),
    validate="one_to_one",
)
print("多列键与 suffixes:")
print(multi_key)

left_indexed = left.set_index("key")
right_indexed = right.set_index("key")
index_merge = left_indexed.merge(
    right_indexed,
    left_index=True,
    right_index=True,
    how="outer",
    validate="one_to_one",
)
print("\n索引连接:")
print(index_merge)

多列键与 suffixes:
  group  year  score_exam1  score_exam2
0     A  2025           80           82
1     A  2026           90           93
2     B  2026           85           88

索引连接:
     value label
key
K0      10     A
K1      20     B
K2      30     C
K3      40   NaN

## 11. 透视表：把长表变成汇总矩阵

In [22]:
# pivot_table 按 index/columns 两个维度分组，并聚合 values。
pivot = pd.pivot_table(
    clean,
    index="city",
    columns="category",
    values="revenue",
    aggfunc="sum",
    fill_value=0,
    margins=True,
)
pivot

category   Book   Food   Tech    All
city
Beijing   216.0    0.0    0.0  216.0
Shanghai    0.0    0.0  483.0  483.0
Shenzhen    0.0   90.0    0.0   90.0
Unknown     0.0  100.0    0.0  100.0
All       216.0  190.0  483.0  889.0

## 12. 方法链与可读的数据管道

方法链让处理顺序从上到下可读。复杂业务逻辑可放到 `.pipe()` 调用的小函数中。

In [23]:
def add_discounted_revenue(df: pd.DataFrame, rate: float) -> pd.DataFrame:
    return df.assign(net_revenue=df["revenue"] * (1 - rate))


report = (
    clean.loc[clean["revenue"] > 50]
    # pipe 把当前 DataFrame 传给自定义函数，便于保持方法链从上到下阅读。
.pipe(add_discounted_revenue, rate=0.10)
    .groupby("city", as_index=False)
    .agg(net_revenue=("net_revenue", "sum"))
    .sort_values("net_revenue", ascending=False)
    .reset_index(drop=True)
)
report

       city  net_revenue
0  Shanghai        434.7
1   Beijing        194.4
2   Unknown         90.0
3  Shenzhen         81.0

## 13. 快速可视化

Pandas 的 `.plot()` 适合探索；正式报告可进一步使用 Matplotlib / Seaborn 定制。

In [24]:
ax = category_summary.plot.bar(
    x="category",
    y="total_revenue",
    legend=False,
    title="Revenue by category",
    color="#4C78A8",
)
ax.set_xlabel("")
ax.set_ylabel("Revenue")
plt.tight_layout()
plt.show()

/var/folders/fs/nqhyfr317t17_3shs0v7ygdr0000gn/T/ipykernel_68273/923922897.py:11: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

### 随机游走与散点图

`Series.plot()` 可快速画一维序列；`DataFrame.plot.scatter()` 用于观察两个变量的关系。随机游走常用 `cumsum()` 把每一步随机变化累积起来。

In [25]:
plot_rng = np.random.default_rng(42)
random_walk = pd.Series(plot_rng.normal(size=300)).cumsum()
scatter_data = pd.DataFrame({
    "x": plot_rng.normal(size=150),
    "noise": plot_rng.normal(scale=0.6, size=150),
})
scatter_data["y"] = 2 * scatter_data["x"] + scatter_data["noise"]

fig, axes = plt.subplots(1, 2, figsize=(10, 3.5))
random_walk.plot(ax=axes[0], title="Random walk")
scatter_data.plot.scatter(
    x="x", y="y", ax=axes[1], title="Related variables"
)
plt.tight_layout()
plt.show()

/var/folders/fs/nqhyfr317t17_3shs0v7ygdr0000gn/T/ipykernel_68273/3651139254.py:15: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## 14. 常见坑与练习

- 连接前检查键是否唯一，并使用 `validate=`。
- 不要在不理解缺失原因时直接 `dropna()`。
- 避免逐行 `iterrows()`；优先列运算、`groupby`、`merge`。
- `.apply()` 不是万能加速器，能向量化时优先向量化。
- 导出前明确索引是否需要：`to_csv(..., index=False)`。

**练习**

1. 找出每个客户收入最高的一笔订单；
2. 计算每个城市的订单数、总收入和客单价；
3. 把 `category` 转成分类类型，比较内存占用。

In [26]:
# 参考答案
top_order_per_customer = clean.loc[
    clean.groupby("customer")["revenue"].idxmax(),
    ["customer", "order_id", "revenue"],
]

city_summary = (
    clean.groupby("city", as_index=False)
    .agg(
        order_count=("order_id", "nunique"),
        total_revenue=("revenue", "sum"),
        average_order_value=("revenue", "mean"),
    )
)

category_as_text = clean["category"]
category_as_category = clean["category"].astype("category")
print(top_order_per_customer)
print(city_summary)
print("文本内存:", category_as_text.memory_usage(deep=True))
print("分类内存:", category_as_category.memory_usage(deep=True))

  customer  order_id  revenue
2    Alice      1003    126.0
1      Bob      1002    399.0
3     Chen      1004     90.0
5     Dina      1006    100.0
       city  order_count  total_revenue  average_order_value
0   Beijing            2          216.0                108.0
1  Shanghai            2          483.0                241.5
2  Shenzhen            1           90.0                 90.0
3   Unknown            1          100.0                100.0
文本内存: 204
分类内存: 175